FROM golang:1.24.0 AS builder
WORKDIR /miner

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o user-service .

FROM alpine:latest
WORKDIR /root

COPY --from=builder /miner/config.yml .
COPY --from=builder /miner/user-service .

CMD [ "./user-service" ]
