server:
  port: 50011

mysql:
  host: localhost
  port: 33061
  user: root
  password: aaa
  dbname: micro-user
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: localhost
  port: 7000

jwt:
  secret: hello#:)
  expire: 24 # hours

log:
  level: debug
  filename: ./logs/micro-user.log
  max_size: 100
  max_age: 30
  max_backups: 10
