services:
  redis-7001:
    image: redis:latest
    container_name: redis-7001
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./conf/node-7001.conf:/usr/local/etc/redis/redis.conf
      - ./data/7001:/data
    ports:
      - "7001:7001"
    networks:
      - redis-cluster-network

  redis-7002:
    image: redis:latest
    container_name: redis-7002
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./conf/node-7002.conf:/usr/local/etc/redis/redis.conf
      - ./data/7002:/data
    ports:
      - "7002:7002"
    networks:
      - redis-cluster-network

  redis-7003:
    image: redis:latest
    container_name: redis-7003
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./conf/node-7003.conf:/usr/local/etc/redis/redis.conf
      - ./data/7003:/data
    ports:
      - "7003:7003"
    networks:
      - redis-cluster-network

  redis-7004:
    image: redis:latest
    container_name: redis-7004
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./conf/node-7004.conf:/usr/local/etc/redis/redis.conf
      - ./data/7004:/data
    ports:
      - "7004:7004"
    networks:
      - redis-cluster-network

  redis-7005:
    image: redis:latest
    container_name: redis-7005
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./conf/node-7005.conf:/usr/local/etc/redis/redis.conf
      - ./data/7005:/data
    ports:
      - "7005:7005"
    networks:
      - redis-cluster-network

  redis-7006:
    image: redis:latest
    container_name: redis-7006
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./conf/node-7006.conf:/usr/local/etc/redis/redis.conf
      - ./data/7006:/data
    ports:
      - "7006:7006"
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    driver: bridge
